/**:
  ros__parameters:
    robot_name: mobile_manipulator
    manipulator_dof_names:
      - waist_joint
      - shoulder_joint
      - elbow_joint
      - upper_forearm_joint
      - lower_forearm_joint
      - wrist_joint
    orientation_error_calc: 5
    only_manipulator: false
    compensate_topdownEffects: false
    compensate_nonlinearInJointSpace: true
    use_augmented_projections: true
    point_const_vel_max_lineal: 0.3
    point_const_vel_max_angular: 3.14
    Cartesian_position_gains.stiffness.X: 400.0
    Cartesian_position_gains.stiffness.Y: 400.0
    Cartesian_position_gains.stiffness.Z: 400.0
    Cartesian_position_gains.damping_ratios.X: 0.9
    Cartesian_position_gains.damping_ratios.Y: 0.9
    Cartesian_position_gains.damping_ratios.Z: 0.9
    Cartesian_orientation_gains.stiffness.X: 400.0
    Cartesian_orientation_gains.stiffness.Y: 400.0
    Cartesian_orientation_gains.stiffness.Z: 400.0
    Cartesian_orientation_gains.damping_ratios.X: 0.9
    Cartesian_orientation_gains.damping_ratios.Y: 0.9
    Cartesian_orientation_gains.damping_ratios.Z: 0.9
    Joint_tasks_gains.Proportional.Mobile_base: 0.0
    Joint_tasks_gains.Proportional.Manipulator: 0.0
    Joint_tasks_gains.Derivative.Mobile_base: 10.0
    Joint_tasks_gains.Derivative.Manipulator: 60.0
    singularity_handling: 1
    joint_limit_avoidance: 0