// Generated by gencpp from file mobile_manipulator_msgs/JointData.msg
// DO NOT EDIT!


#ifndef MOBILE_MANIPULATOR_MSGS_MESSAGE_JOINTDATA_H
#define MOBILE_MANIPULATOR_MSGS_MESSAGE_JOINTDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mobile_manipulator_msgs/Joints.h>
#include <mobile_manipulator_msgs/Joints.h>

namespace mobile_manipulator_msgs
{
template <class ContainerAllocator>
struct JointData_
{
  typedef JointData_<ContainerAllocator> Type;

  JointData_()
    : actual()
    , desired()  {
    }
  JointData_(const ContainerAllocator& _alloc)
    : actual(_alloc)
    , desired(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mobile_manipulator_msgs::Joints_<ContainerAllocator>  _actual_type;
  _actual_type actual;

   typedef  ::mobile_manipulator_msgs::Joints_<ContainerAllocator>  _desired_type;
  _desired_type desired;





  typedef boost::shared_ptr< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> const> ConstPtr;

}; // struct JointData_

typedef ::mobile_manipulator_msgs::JointData_<std::allocator<void> > JointData;

typedef boost::shared_ptr< ::mobile_manipulator_msgs::JointData > JointDataPtr;
typedef boost::shared_ptr< ::mobile_manipulator_msgs::JointData const> JointDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_manipulator_msgs::JointData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_manipulator_msgs::JointData_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::JointData_<ContainerAllocator2> & rhs)
{
  return lhs.actual == rhs.actual &&
    lhs.desired == rhs.desired;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_manipulator_msgs::JointData_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::JointData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9180821b4f48e275f64a7616084c29b";
  }

  static const char* value(const ::mobile_manipulator_msgs::JointData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9180821b4f48e27ULL;
  static const uint64_t static_value2 = 0x5f64a7616084c29bULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_manipulator_msgs/JointData";
  }

  static const char* value(const ::mobile_manipulator_msgs::JointData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Joints actual\n"
"Joints desired\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/Joints\n"
"float32 mobjoint1\n"
"float32 mobjoint2\n"
"float32 mobjoint3\n"
"float32 joint1\n"
"float32 joint2\n"
"float32 joint3\n"
"float32 joint4\n"
"float32 joint5\n"
"float32 joint6\n"
;
  }

  static const char* value(const ::mobile_manipulator_msgs::JointData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actual);
      stream.next(m.desired);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_manipulator_msgs::JointData_<ContainerAllocator>& v)
  {
    s << indent << "actual: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >::stream(s, indent + "  ", v.actual);
    s << indent << "desired: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >::stream(s, indent + "  ", v.desired);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_MANIPULATOR_MSGS_MESSAGE_JOINTDATA_H
