// Generated by gencpp from file mobile_manipulator_msgs/Joints.msg
// DO NOT EDIT!


#ifndef MOBILE_MANIPULATOR_MSGS_MESSAGE_JOINTS_H
#define MOBILE_MANIPULATOR_MSGS_MESSAGE_JOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_manipulator_msgs
{
template <class ContainerAllocator>
struct Joints_
{
  typedef Joints_<ContainerAllocator> Type;

  Joints_()
    : mobjoint1(0.0)
    , mobjoint2(0.0)
    , mobjoint3(0.0)
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)  {
    }
  Joints_(const ContainerAllocator& _alloc)
    : mobjoint1(0.0)
    , mobjoint2(0.0)
    , mobjoint3(0.0)
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)  {
  (void)_alloc;
    }



   typedef float _mobjoint1_type;
  _mobjoint1_type mobjoint1;

   typedef float _mobjoint2_type;
  _mobjoint2_type mobjoint2;

   typedef float _mobjoint3_type;
  _mobjoint3_type mobjoint3;

   typedef float _joint1_type;
  _joint1_type joint1;

   typedef float _joint2_type;
  _joint2_type joint2;

   typedef float _joint3_type;
  _joint3_type joint3;

   typedef float _joint4_type;
  _joint4_type joint4;

   typedef float _joint5_type;
  _joint5_type joint5;

   typedef float _joint6_type;
  _joint6_type joint6;





  typedef boost::shared_ptr< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> const> ConstPtr;

}; // struct Joints_

typedef ::mobile_manipulator_msgs::Joints_<std::allocator<void> > Joints;

typedef boost::shared_ptr< ::mobile_manipulator_msgs::Joints > JointsPtr;
typedef boost::shared_ptr< ::mobile_manipulator_msgs::Joints const> JointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_manipulator_msgs::Joints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_manipulator_msgs::Joints_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::Joints_<ContainerAllocator2> & rhs)
{
  return lhs.mobjoint1 == rhs.mobjoint1 &&
    lhs.mobjoint2 == rhs.mobjoint2 &&
    lhs.mobjoint3 == rhs.mobjoint3 &&
    lhs.joint1 == rhs.joint1 &&
    lhs.joint2 == rhs.joint2 &&
    lhs.joint3 == rhs.joint3 &&
    lhs.joint4 == rhs.joint4 &&
    lhs.joint5 == rhs.joint5 &&
    lhs.joint6 == rhs.joint6;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_manipulator_msgs::Joints_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::Joints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "427db072ec8a3fb3a8c98dd68eb3c84d";
  }

  static const char* value(const ::mobile_manipulator_msgs::Joints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x427db072ec8a3fb3ULL;
  static const uint64_t static_value2 = 0xa8c98dd68eb3c84dULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_manipulator_msgs/Joints";
  }

  static const char* value(const ::mobile_manipulator_msgs::Joints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 mobjoint1\n"
"float32 mobjoint2\n"
"float32 mobjoint3\n"
"float32 joint1\n"
"float32 joint2\n"
"float32 joint3\n"
"float32 joint4\n"
"float32 joint5\n"
"float32 joint6\n"
;
  }

  static const char* value(const ::mobile_manipulator_msgs::Joints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mobjoint1);
      stream.next(m.mobjoint2);
      stream.next(m.mobjoint3);
      stream.next(m.joint1);
      stream.next(m.joint2);
      stream.next(m.joint3);
      stream.next(m.joint4);
      stream.next(m.joint5);
      stream.next(m.joint6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_manipulator_msgs::Joints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_manipulator_msgs::Joints_<ContainerAllocator>& v)
  {
    s << indent << "mobjoint1: ";
    Printer<float>::stream(s, indent + "  ", v.mobjoint1);
    s << indent << "mobjoint2: ";
    Printer<float>::stream(s, indent + "  ", v.mobjoint2);
    s << indent << "mobjoint3: ";
    Printer<float>::stream(s, indent + "  ", v.mobjoint3);
    s << indent << "joint1: ";
    Printer<float>::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    Printer<float>::stream(s, indent + "  ", v.joint2);
    s << indent << "joint3: ";
    Printer<float>::stream(s, indent + "  ", v.joint3);
    s << indent << "joint4: ";
    Printer<float>::stream(s, indent + "  ", v.joint4);
    s << indent << "joint5: ";
    Printer<float>::stream(s, indent + "  ", v.joint5);
    s << indent << "joint6: ";
    Printer<float>::stream(s, indent + "  ", v.joint6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_MANIPULATOR_MSGS_MESSAGE_JOINTS_H
