// Generated by gencpp from file mobile_manipulator_msgs/MobileManipulator.msg
// DO NOT EDIT!


#ifndef MOBILE_MANIPULATOR_MSGS_MESSAGE_MOBILEMANIPULATOR_H
#define MOBILE_MANIPULATOR_MSGS_MESSAGE_MOBILEMANIPULATOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mobile_manipulator_msgs/PositionData.h>
#include <mobile_manipulator_msgs/OrientationData.h>
#include <mobile_manipulator_msgs/SingularValues.h>
#include <mobile_manipulator_msgs/Torques.h>
#include <mobile_manipulator_msgs/JointData.h>

namespace mobile_manipulator_msgs
{
template <class ContainerAllocator>
struct MobileManipulator_
{
  typedef MobileManipulator_<ContainerAllocator> Type;

  MobileManipulator_()
    : header()
    , position()
    , orientation()
    , singular()
    , torques()
    , joints()  {
    }
  MobileManipulator_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , orientation(_alloc)
    , singular(_alloc)
    , torques(_alloc)
    , joints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::mobile_manipulator_msgs::PositionData_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator>  _singular_type;
  _singular_type singular;

   typedef  ::mobile_manipulator_msgs::Torques_<ContainerAllocator>  _torques_type;
  _torques_type torques;

   typedef  ::mobile_manipulator_msgs::JointData_<ContainerAllocator>  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> const> ConstPtr;

}; // struct MobileManipulator_

typedef ::mobile_manipulator_msgs::MobileManipulator_<std::allocator<void> > MobileManipulator;

typedef boost::shared_ptr< ::mobile_manipulator_msgs::MobileManipulator > MobileManipulatorPtr;
typedef boost::shared_ptr< ::mobile_manipulator_msgs::MobileManipulator const> MobileManipulatorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation &&
    lhs.singular == rhs.singular &&
    lhs.torques == rhs.torques &&
    lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b292abda1dc86e0e527bfb472074f00f";
  }

  static const char* value(const ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb292abda1dc86e0eULL;
  static const uint64_t static_value2 = 0x527bfb472074f00fULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_manipulator_msgs/MobileManipulator";
  }

  static const char* value(const ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"PositionData position\n"
"OrientationData orientation\n"
"SingularValues singular\n"
"Torques torques\n"
"JointData joints\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/PositionData\n"
"Vector3 current_position\n"
"Vector3 desired_position\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/Vector3\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/OrientationData\n"
"RPY current_orient\n"
"RPY desired_orient\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/RPY\n"
"# Orientation of a reference frame\n"
"\n"
"# Fixed-axis roll, in radians\n"
"float32 roll\n"
"\n"
"# Fixed-axis pitch, in radians\n"
"float32 pitch\n"
"\n"
"# Fixed-axis yaw, in radians\n"
"float32 yaw\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/SingularValues\n"
"float32 min_pos_sv\n"
"float32 min_ori_sv\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/Torques\n"
"float32 torque1\n"
"float32 torque2\n"
"float32 torque3\n"
"float32 torque4\n"
"float32 torque5\n"
"float32 torque6\n"
"float32 torque7\n"
"float32 torque8\n"
"float32 torque9\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/JointData\n"
"Joints actual\n"
"Joints desired\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/Joints\n"
"float32 mobjoint1\n"
"float32 mobjoint2\n"
"float32 mobjoint3\n"
"float32 joint1\n"
"float32 joint2\n"
"float32 joint3\n"
"float32 joint4\n"
"float32 joint5\n"
"float32 joint6\n"
;
  }

  static const char* value(const ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.singular);
      stream.next(m.torques);
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MobileManipulator_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_manipulator_msgs::MobileManipulator_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "singular: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >::stream(s, indent + "  ", v.singular);
    s << indent << "torques: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >::stream(s, indent + "  ", v.torques);
    s << indent << "joints: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::JointData_<ContainerAllocator> >::stream(s, indent + "  ", v.joints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_MANIPULATOR_MSGS_MESSAGE_MOBILEMANIPULATOR_H
