// Generated by gencpp from file mobile_manipulator_msgs/OrientationData.msg
// DO NOT EDIT!


#ifndef MOBILE_MANIPULATOR_MSGS_MESSAGE_ORIENTATIONDATA_H
#define MOBILE_MANIPULATOR_MSGS_MESSAGE_ORIENTATIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mobile_manipulator_msgs/RPY.h>
#include <mobile_manipulator_msgs/RPY.h>

namespace mobile_manipulator_msgs
{
template <class ContainerAllocator>
struct OrientationData_
{
  typedef OrientationData_<ContainerAllocator> Type;

  OrientationData_()
    : current_orient()
    , desired_orient()  {
    }
  OrientationData_(const ContainerAllocator& _alloc)
    : current_orient(_alloc)
    , desired_orient(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mobile_manipulator_msgs::RPY_<ContainerAllocator>  _current_orient_type;
  _current_orient_type current_orient;

   typedef  ::mobile_manipulator_msgs::RPY_<ContainerAllocator>  _desired_orient_type;
  _desired_orient_type desired_orient;





  typedef boost::shared_ptr< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> const> ConstPtr;

}; // struct OrientationData_

typedef ::mobile_manipulator_msgs::OrientationData_<std::allocator<void> > OrientationData;

typedef boost::shared_ptr< ::mobile_manipulator_msgs::OrientationData > OrientationDataPtr;
typedef boost::shared_ptr< ::mobile_manipulator_msgs::OrientationData const> OrientationDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator2> & rhs)
{
  return lhs.current_orient == rhs.current_orient &&
    lhs.desired_orient == rhs.desired_orient;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ea91799dc6fd84b700660686d98fd66";
  }

  static const char* value(const ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ea91799dc6fd84bULL;
  static const uint64_t static_value2 = 0x700660686d98fd66ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_manipulator_msgs/OrientationData";
  }

  static const char* value(const ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RPY current_orient\n"
"RPY desired_orient\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/RPY\n"
"# Orientation of a reference frame\n"
"\n"
"# Fixed-axis roll, in radians\n"
"float32 roll\n"
"\n"
"# Fixed-axis pitch, in radians\n"
"float32 pitch\n"
"\n"
"# Fixed-axis yaw, in radians\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_orient);
      stream.next(m.desired_orient);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrientationData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_manipulator_msgs::OrientationData_<ContainerAllocator>& v)
  {
    s << indent << "current_orient: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::RPY_<ContainerAllocator> >::stream(s, indent + "  ", v.current_orient);
    s << indent << "desired_orient: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::RPY_<ContainerAllocator> >::stream(s, indent + "  ", v.desired_orient);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_MANIPULATOR_MSGS_MESSAGE_ORIENTATIONDATA_H
