// Generated by gencpp from file mobile_manipulator_msgs/PositionData.msg
// DO NOT EDIT!


#ifndef MOBILE_MANIPULATOR_MSGS_MESSAGE_POSITIONDATA_H
#define MOBILE_MANIPULATOR_MSGS_MESSAGE_POSITIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mobile_manipulator_msgs/Vector3.h>
#include <mobile_manipulator_msgs/Vector3.h>

namespace mobile_manipulator_msgs
{
template <class ContainerAllocator>
struct PositionData_
{
  typedef PositionData_<ContainerAllocator> Type;

  PositionData_()
    : current_position()
    , desired_position()  {
    }
  PositionData_(const ContainerAllocator& _alloc)
    : current_position(_alloc)
    , desired_position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mobile_manipulator_msgs::Vector3_<ContainerAllocator>  _current_position_type;
  _current_position_type current_position;

   typedef  ::mobile_manipulator_msgs::Vector3_<ContainerAllocator>  _desired_position_type;
  _desired_position_type desired_position;





  typedef boost::shared_ptr< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> const> ConstPtr;

}; // struct PositionData_

typedef ::mobile_manipulator_msgs::PositionData_<std::allocator<void> > PositionData;

typedef boost::shared_ptr< ::mobile_manipulator_msgs::PositionData > PositionDataPtr;
typedef boost::shared_ptr< ::mobile_manipulator_msgs::PositionData const> PositionDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_manipulator_msgs::PositionData_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::PositionData_<ContainerAllocator2> & rhs)
{
  return lhs.current_position == rhs.current_position &&
    lhs.desired_position == rhs.desired_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_manipulator_msgs::PositionData_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::PositionData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6920a2c98186d4bf709632ac111101d";
  }

  static const char* value(const ::mobile_manipulator_msgs::PositionData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6920a2c98186d4bULL;
  static const uint64_t static_value2 = 0xf709632ac111101dULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_manipulator_msgs/PositionData";
  }

  static const char* value(const ::mobile_manipulator_msgs::PositionData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Vector3 current_position\n"
"Vector3 desired_position\n"
"================================================================================\n"
"MSG: mobile_manipulator_msgs/Vector3\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::mobile_manipulator_msgs::PositionData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_position);
      stream.next(m.desired_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_manipulator_msgs::PositionData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_manipulator_msgs::PositionData_<ContainerAllocator>& v)
  {
    s << indent << "current_position: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.current_position);
    s << indent << "desired_position: ";
    s << std::endl;
    Printer< ::mobile_manipulator_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.desired_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_MANIPULATOR_MSGS_MESSAGE_POSITIONDATA_H
