// Generated by gencpp from file mobile_manipulator_msgs/SingularValues.msg
// DO NOT EDIT!


#ifndef MOBILE_MANIPULATOR_MSGS_MESSAGE_SINGULARVALUES_H
#define MOBILE_MANIPULATOR_MSGS_MESSAGE_SINGULARVALUES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_manipulator_msgs
{
template <class ContainerAllocator>
struct SingularValues_
{
  typedef SingularValues_<ContainerAllocator> Type;

  SingularValues_()
    : min_pos_sv(0.0)
    , min_ori_sv(0.0)  {
    }
  SingularValues_(const ContainerAllocator& _alloc)
    : min_pos_sv(0.0)
    , min_ori_sv(0.0)  {
  (void)_alloc;
    }



   typedef float _min_pos_sv_type;
  _min_pos_sv_type min_pos_sv;

   typedef float _min_ori_sv_type;
  _min_ori_sv_type min_ori_sv;





  typedef boost::shared_ptr< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> const> ConstPtr;

}; // struct SingularValues_

typedef ::mobile_manipulator_msgs::SingularValues_<std::allocator<void> > SingularValues;

typedef boost::shared_ptr< ::mobile_manipulator_msgs::SingularValues > SingularValuesPtr;
typedef boost::shared_ptr< ::mobile_manipulator_msgs::SingularValues const> SingularValuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator2> & rhs)
{
  return lhs.min_pos_sv == rhs.min_pos_sv &&
    lhs.min_ori_sv == rhs.min_ori_sv;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9c78d5181449c9ee849e15fab621090";
  }

  static const char* value(const ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9c78d5181449c9eULL;
  static const uint64_t static_value2 = 0xe849e15fab621090ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_manipulator_msgs/SingularValues";
  }

  static const char* value(const ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 min_pos_sv\n"
"float32 min_ori_sv\n"
;
  }

  static const char* value(const ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min_pos_sv);
      stream.next(m.min_ori_sv);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SingularValues_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_manipulator_msgs::SingularValues_<ContainerAllocator>& v)
  {
    s << indent << "min_pos_sv: ";
    Printer<float>::stream(s, indent + "  ", v.min_pos_sv);
    s << indent << "min_ori_sv: ";
    Printer<float>::stream(s, indent + "  ", v.min_ori_sv);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_MANIPULATOR_MSGS_MESSAGE_SINGULARVALUES_H
