// Generated by gencpp from file mobile_manipulator_msgs/Torques.msg
// DO NOT EDIT!


#ifndef MOBILE_MANIPULATOR_MSGS_MESSAGE_TORQUES_H
#define MOBILE_MANIPULATOR_MSGS_MESSAGE_TORQUES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_manipulator_msgs
{
template <class ContainerAllocator>
struct Torques_
{
  typedef Torques_<ContainerAllocator> Type;

  Torques_()
    : torque1(0.0)
    , torque2(0.0)
    , torque3(0.0)
    , torque4(0.0)
    , torque5(0.0)
    , torque6(0.0)
    , torque7(0.0)
    , torque8(0.0)
    , torque9(0.0)  {
    }
  Torques_(const ContainerAllocator& _alloc)
    : torque1(0.0)
    , torque2(0.0)
    , torque3(0.0)
    , torque4(0.0)
    , torque5(0.0)
    , torque6(0.0)
    , torque7(0.0)
    , torque8(0.0)
    , torque9(0.0)  {
  (void)_alloc;
    }



   typedef float _torque1_type;
  _torque1_type torque1;

   typedef float _torque2_type;
  _torque2_type torque2;

   typedef float _torque3_type;
  _torque3_type torque3;

   typedef float _torque4_type;
  _torque4_type torque4;

   typedef float _torque5_type;
  _torque5_type torque5;

   typedef float _torque6_type;
  _torque6_type torque6;

   typedef float _torque7_type;
  _torque7_type torque7;

   typedef float _torque8_type;
  _torque8_type torque8;

   typedef float _torque9_type;
  _torque9_type torque9;





  typedef boost::shared_ptr< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> const> ConstPtr;

}; // struct Torques_

typedef ::mobile_manipulator_msgs::Torques_<std::allocator<void> > Torques;

typedef boost::shared_ptr< ::mobile_manipulator_msgs::Torques > TorquesPtr;
typedef boost::shared_ptr< ::mobile_manipulator_msgs::Torques const> TorquesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_manipulator_msgs::Torques_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_manipulator_msgs::Torques_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::Torques_<ContainerAllocator2> & rhs)
{
  return lhs.torque1 == rhs.torque1 &&
    lhs.torque2 == rhs.torque2 &&
    lhs.torque3 == rhs.torque3 &&
    lhs.torque4 == rhs.torque4 &&
    lhs.torque5 == rhs.torque5 &&
    lhs.torque6 == rhs.torque6 &&
    lhs.torque7 == rhs.torque7 &&
    lhs.torque8 == rhs.torque8 &&
    lhs.torque9 == rhs.torque9;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_manipulator_msgs::Torques_<ContainerAllocator1> & lhs, const ::mobile_manipulator_msgs::Torques_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51af3a57814ea678a622d88758f096dc";
  }

  static const char* value(const ::mobile_manipulator_msgs::Torques_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51af3a57814ea678ULL;
  static const uint64_t static_value2 = 0xa622d88758f096dcULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_manipulator_msgs/Torques";
  }

  static const char* value(const ::mobile_manipulator_msgs::Torques_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 torque1\n"
"float32 torque2\n"
"float32 torque3\n"
"float32 torque4\n"
"float32 torque5\n"
"float32 torque6\n"
"float32 torque7\n"
"float32 torque8\n"
"float32 torque9\n"
;
  }

  static const char* value(const ::mobile_manipulator_msgs::Torques_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.torque1);
      stream.next(m.torque2);
      stream.next(m.torque3);
      stream.next(m.torque4);
      stream.next(m.torque5);
      stream.next(m.torque6);
      stream.next(m.torque7);
      stream.next(m.torque8);
      stream.next(m.torque9);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Torques_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_manipulator_msgs::Torques_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_manipulator_msgs::Torques_<ContainerAllocator>& v)
  {
    s << indent << "torque1: ";
    Printer<float>::stream(s, indent + "  ", v.torque1);
    s << indent << "torque2: ";
    Printer<float>::stream(s, indent + "  ", v.torque2);
    s << indent << "torque3: ";
    Printer<float>::stream(s, indent + "  ", v.torque3);
    s << indent << "torque4: ";
    Printer<float>::stream(s, indent + "  ", v.torque4);
    s << indent << "torque5: ";
    Printer<float>::stream(s, indent + "  ", v.torque5);
    s << indent << "torque6: ";
    Printer<float>::stream(s, indent + "  ", v.torque6);
    s << indent << "torque7: ";
    Printer<float>::stream(s, indent + "  ", v.torque7);
    s << indent << "torque8: ";
    Printer<float>::stream(s, indent + "  ", v.torque8);
    s << indent << "torque9: ";
    Printer<float>::stream(s, indent + "  ", v.torque9);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_MANIPULATOR_MSGS_MESSAGE_TORQUES_H
