# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mobile_manipulator_msgs/JointData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mobile_manipulator_msgs.msg

class JointData(genpy.Message):
  _md5sum = "b9180821b4f48e275f64a7616084c29b"
  _type = "mobile_manipulator_msgs/JointData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Joints actual
Joints desired
================================================================================
MSG: mobile_manipulator_msgs/Joints
float32 mobjoint1
float32 mobjoint2
float32 mobjoint3
float32 joint1
float32 joint2
float32 joint3
float32 joint4
float32 joint5
float32 joint6"""
  __slots__ = ['actual','desired']
  _slot_types = ['mobile_manipulator_msgs/Joints','mobile_manipulator_msgs/Joints']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       actual,desired

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.actual is None:
        self.actual = mobile_manipulator_msgs.msg.Joints()
      if self.desired is None:
        self.desired = mobile_manipulator_msgs.msg.Joints()
    else:
      self.actual = mobile_manipulator_msgs.msg.Joints()
      self.desired = mobile_manipulator_msgs.msg.Joints()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_18f().pack(_x.actual.mobjoint1, _x.actual.mobjoint2, _x.actual.mobjoint3, _x.actual.joint1, _x.actual.joint2, _x.actual.joint3, _x.actual.joint4, _x.actual.joint5, _x.actual.joint6, _x.desired.mobjoint1, _x.desired.mobjoint2, _x.desired.mobjoint3, _x.desired.joint1, _x.desired.joint2, _x.desired.joint3, _x.desired.joint4, _x.desired.joint5, _x.desired.joint6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.actual is None:
        self.actual = mobile_manipulator_msgs.msg.Joints()
      if self.desired is None:
        self.desired = mobile_manipulator_msgs.msg.Joints()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.actual.mobjoint1, _x.actual.mobjoint2, _x.actual.mobjoint3, _x.actual.joint1, _x.actual.joint2, _x.actual.joint3, _x.actual.joint4, _x.actual.joint5, _x.actual.joint6, _x.desired.mobjoint1, _x.desired.mobjoint2, _x.desired.mobjoint3, _x.desired.joint1, _x.desired.joint2, _x.desired.joint3, _x.desired.joint4, _x.desired.joint5, _x.desired.joint6,) = _get_struct_18f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_18f().pack(_x.actual.mobjoint1, _x.actual.mobjoint2, _x.actual.mobjoint3, _x.actual.joint1, _x.actual.joint2, _x.actual.joint3, _x.actual.joint4, _x.actual.joint5, _x.actual.joint6, _x.desired.mobjoint1, _x.desired.mobjoint2, _x.desired.mobjoint3, _x.desired.joint1, _x.desired.joint2, _x.desired.joint3, _x.desired.joint4, _x.desired.joint5, _x.desired.joint6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.actual is None:
        self.actual = mobile_manipulator_msgs.msg.Joints()
      if self.desired is None:
        self.desired = mobile_manipulator_msgs.msg.Joints()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.actual.mobjoint1, _x.actual.mobjoint2, _x.actual.mobjoint3, _x.actual.joint1, _x.actual.joint2, _x.actual.joint3, _x.actual.joint4, _x.actual.joint5, _x.actual.joint6, _x.desired.mobjoint1, _x.desired.mobjoint2, _x.desired.mobjoint3, _x.desired.joint1, _x.desired.joint2, _x.desired.joint3, _x.desired.joint4, _x.desired.joint5, _x.desired.joint6,) = _get_struct_18f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18f = None
def _get_struct_18f():
    global _struct_18f
    if _struct_18f is None:
        _struct_18f = struct.Struct("<18f")
    return _struct_18f
