# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mobile_manipulator_msgs/MobileManipulator.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mobile_manipulator_msgs.msg
import std_msgs.msg

class MobileManipulator(genpy.Message):
  _md5sum = "b292abda1dc86e0e527bfb472074f00f"
  _type = "mobile_manipulator_msgs/MobileManipulator"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
PositionData position
OrientationData orientation
SingularValues singular
Torques torques
JointData joints
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: mobile_manipulator_msgs/PositionData
Vector3 current_position
Vector3 desired_position
================================================================================
MSG: mobile_manipulator_msgs/Vector3
float32 x
float32 y
float32 z
================================================================================
MSG: mobile_manipulator_msgs/OrientationData
RPY current_orient
RPY desired_orient
================================================================================
MSG: mobile_manipulator_msgs/RPY
# Orientation of a reference frame

# Fixed-axis roll, in radians
float32 roll

# Fixed-axis pitch, in radians
float32 pitch

# Fixed-axis yaw, in radians
float32 yaw
================================================================================
MSG: mobile_manipulator_msgs/SingularValues
float32 min_pos_sv
float32 min_ori_sv
================================================================================
MSG: mobile_manipulator_msgs/Torques
float32 torque1
float32 torque2
float32 torque3
float32 torque4
float32 torque5
float32 torque6
float32 torque7
float32 torque8
float32 torque9
================================================================================
MSG: mobile_manipulator_msgs/JointData
Joints actual
Joints desired
================================================================================
MSG: mobile_manipulator_msgs/Joints
float32 mobjoint1
float32 mobjoint2
float32 mobjoint3
float32 joint1
float32 joint2
float32 joint3
float32 joint4
float32 joint5
float32 joint6"""
  __slots__ = ['header','position','orientation','singular','torques','joints']
  _slot_types = ['std_msgs/Header','mobile_manipulator_msgs/PositionData','mobile_manipulator_msgs/OrientationData','mobile_manipulator_msgs/SingularValues','mobile_manipulator_msgs/Torques','mobile_manipulator_msgs/JointData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,position,orientation,singular,torques,joints

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MobileManipulator, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = mobile_manipulator_msgs.msg.PositionData()
      if self.orientation is None:
        self.orientation = mobile_manipulator_msgs.msg.OrientationData()
      if self.singular is None:
        self.singular = mobile_manipulator_msgs.msg.SingularValues()
      if self.torques is None:
        self.torques = mobile_manipulator_msgs.msg.Torques()
      if self.joints is None:
        self.joints = mobile_manipulator_msgs.msg.JointData()
    else:
      self.header = std_msgs.msg.Header()
      self.position = mobile_manipulator_msgs.msg.PositionData()
      self.orientation = mobile_manipulator_msgs.msg.OrientationData()
      self.singular = mobile_manipulator_msgs.msg.SingularValues()
      self.torques = mobile_manipulator_msgs.msg.Torques()
      self.joints = mobile_manipulator_msgs.msg.JointData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_41f().pack(_x.position.current_position.x, _x.position.current_position.y, _x.position.current_position.z, _x.position.desired_position.x, _x.position.desired_position.y, _x.position.desired_position.z, _x.orientation.current_orient.roll, _x.orientation.current_orient.pitch, _x.orientation.current_orient.yaw, _x.orientation.desired_orient.roll, _x.orientation.desired_orient.pitch, _x.orientation.desired_orient.yaw, _x.singular.min_pos_sv, _x.singular.min_ori_sv, _x.torques.torque1, _x.torques.torque2, _x.torques.torque3, _x.torques.torque4, _x.torques.torque5, _x.torques.torque6, _x.torques.torque7, _x.torques.torque8, _x.torques.torque9, _x.joints.actual.mobjoint1, _x.joints.actual.mobjoint2, _x.joints.actual.mobjoint3, _x.joints.actual.joint1, _x.joints.actual.joint2, _x.joints.actual.joint3, _x.joints.actual.joint4, _x.joints.actual.joint5, _x.joints.actual.joint6, _x.joints.desired.mobjoint1, _x.joints.desired.mobjoint2, _x.joints.desired.mobjoint3, _x.joints.desired.joint1, _x.joints.desired.joint2, _x.joints.desired.joint3, _x.joints.desired.joint4, _x.joints.desired.joint5, _x.joints.desired.joint6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = mobile_manipulator_msgs.msg.PositionData()
      if self.orientation is None:
        self.orientation = mobile_manipulator_msgs.msg.OrientationData()
      if self.singular is None:
        self.singular = mobile_manipulator_msgs.msg.SingularValues()
      if self.torques is None:
        self.torques = mobile_manipulator_msgs.msg.Torques()
      if self.joints is None:
        self.joints = mobile_manipulator_msgs.msg.JointData()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 164
      (_x.position.current_position.x, _x.position.current_position.y, _x.position.current_position.z, _x.position.desired_position.x, _x.position.desired_position.y, _x.position.desired_position.z, _x.orientation.current_orient.roll, _x.orientation.current_orient.pitch, _x.orientation.current_orient.yaw, _x.orientation.desired_orient.roll, _x.orientation.desired_orient.pitch, _x.orientation.desired_orient.yaw, _x.singular.min_pos_sv, _x.singular.min_ori_sv, _x.torques.torque1, _x.torques.torque2, _x.torques.torque3, _x.torques.torque4, _x.torques.torque5, _x.torques.torque6, _x.torques.torque7, _x.torques.torque8, _x.torques.torque9, _x.joints.actual.mobjoint1, _x.joints.actual.mobjoint2, _x.joints.actual.mobjoint3, _x.joints.actual.joint1, _x.joints.actual.joint2, _x.joints.actual.joint3, _x.joints.actual.joint4, _x.joints.actual.joint5, _x.joints.actual.joint6, _x.joints.desired.mobjoint1, _x.joints.desired.mobjoint2, _x.joints.desired.mobjoint3, _x.joints.desired.joint1, _x.joints.desired.joint2, _x.joints.desired.joint3, _x.joints.desired.joint4, _x.joints.desired.joint5, _x.joints.desired.joint6,) = _get_struct_41f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_41f().pack(_x.position.current_position.x, _x.position.current_position.y, _x.position.current_position.z, _x.position.desired_position.x, _x.position.desired_position.y, _x.position.desired_position.z, _x.orientation.current_orient.roll, _x.orientation.current_orient.pitch, _x.orientation.current_orient.yaw, _x.orientation.desired_orient.roll, _x.orientation.desired_orient.pitch, _x.orientation.desired_orient.yaw, _x.singular.min_pos_sv, _x.singular.min_ori_sv, _x.torques.torque1, _x.torques.torque2, _x.torques.torque3, _x.torques.torque4, _x.torques.torque5, _x.torques.torque6, _x.torques.torque7, _x.torques.torque8, _x.torques.torque9, _x.joints.actual.mobjoint1, _x.joints.actual.mobjoint2, _x.joints.actual.mobjoint3, _x.joints.actual.joint1, _x.joints.actual.joint2, _x.joints.actual.joint3, _x.joints.actual.joint4, _x.joints.actual.joint5, _x.joints.actual.joint6, _x.joints.desired.mobjoint1, _x.joints.desired.mobjoint2, _x.joints.desired.mobjoint3, _x.joints.desired.joint1, _x.joints.desired.joint2, _x.joints.desired.joint3, _x.joints.desired.joint4, _x.joints.desired.joint5, _x.joints.desired.joint6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = mobile_manipulator_msgs.msg.PositionData()
      if self.orientation is None:
        self.orientation = mobile_manipulator_msgs.msg.OrientationData()
      if self.singular is None:
        self.singular = mobile_manipulator_msgs.msg.SingularValues()
      if self.torques is None:
        self.torques = mobile_manipulator_msgs.msg.Torques()
      if self.joints is None:
        self.joints = mobile_manipulator_msgs.msg.JointData()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 164
      (_x.position.current_position.x, _x.position.current_position.y, _x.position.current_position.z, _x.position.desired_position.x, _x.position.desired_position.y, _x.position.desired_position.z, _x.orientation.current_orient.roll, _x.orientation.current_orient.pitch, _x.orientation.current_orient.yaw, _x.orientation.desired_orient.roll, _x.orientation.desired_orient.pitch, _x.orientation.desired_orient.yaw, _x.singular.min_pos_sv, _x.singular.min_ori_sv, _x.torques.torque1, _x.torques.torque2, _x.torques.torque3, _x.torques.torque4, _x.torques.torque5, _x.torques.torque6, _x.torques.torque7, _x.torques.torque8, _x.torques.torque9, _x.joints.actual.mobjoint1, _x.joints.actual.mobjoint2, _x.joints.actual.mobjoint3, _x.joints.actual.joint1, _x.joints.actual.joint2, _x.joints.actual.joint3, _x.joints.actual.joint4, _x.joints.actual.joint5, _x.joints.actual.joint6, _x.joints.desired.mobjoint1, _x.joints.desired.mobjoint2, _x.joints.desired.mobjoint3, _x.joints.desired.joint1, _x.joints.desired.joint2, _x.joints.desired.joint3, _x.joints.desired.joint4, _x.joints.desired.joint5, _x.joints.desired.joint6,) = _get_struct_41f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_41f = None
def _get_struct_41f():
    global _struct_41f
    if _struct_41f is None:
        _struct_41f = struct.Struct("<41f")
    return _struct_41f
