# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mobile_manipulator_msgs/OrientationData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mobile_manipulator_msgs.msg

class OrientationData(genpy.Message):
  _md5sum = "0ea91799dc6fd84b700660686d98fd66"
  _type = "mobile_manipulator_msgs/OrientationData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """RPY current_orient
RPY desired_orient
================================================================================
MSG: mobile_manipulator_msgs/RPY
# Orientation of a reference frame

# Fixed-axis roll, in radians
float32 roll

# Fixed-axis pitch, in radians
float32 pitch

# Fixed-axis yaw, in radians
float32 yaw"""
  __slots__ = ['current_orient','desired_orient']
  _slot_types = ['mobile_manipulator_msgs/RPY','mobile_manipulator_msgs/RPY']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       current_orient,desired_orient

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OrientationData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.current_orient is None:
        self.current_orient = mobile_manipulator_msgs.msg.RPY()
      if self.desired_orient is None:
        self.desired_orient = mobile_manipulator_msgs.msg.RPY()
    else:
      self.current_orient = mobile_manipulator_msgs.msg.RPY()
      self.desired_orient = mobile_manipulator_msgs.msg.RPY()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.current_orient.roll, _x.current_orient.pitch, _x.current_orient.yaw, _x.desired_orient.roll, _x.desired_orient.pitch, _x.desired_orient.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.current_orient is None:
        self.current_orient = mobile_manipulator_msgs.msg.RPY()
      if self.desired_orient is None:
        self.desired_orient = mobile_manipulator_msgs.msg.RPY()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.current_orient.roll, _x.current_orient.pitch, _x.current_orient.yaw, _x.desired_orient.roll, _x.desired_orient.pitch, _x.desired_orient.yaw,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.current_orient.roll, _x.current_orient.pitch, _x.current_orient.yaw, _x.desired_orient.roll, _x.desired_orient.pitch, _x.desired_orient.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.current_orient is None:
        self.current_orient = mobile_manipulator_msgs.msg.RPY()
      if self.desired_orient is None:
        self.desired_orient = mobile_manipulator_msgs.msg.RPY()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.current_orient.roll, _x.current_orient.pitch, _x.current_orient.yaw, _x.desired_orient.roll, _x.desired_orient.pitch, _x.desired_orient.yaw,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
