# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mobile_manipulator_msgs/Torques.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Torques(genpy.Message):
  _md5sum = "51af3a57814ea678a622d88758f096dc"
  _type = "mobile_manipulator_msgs/Torques"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 torque1
float32 torque2
float32 torque3
float32 torque4
float32 torque5
float32 torque6
float32 torque7
float32 torque8
float32 torque9"""
  __slots__ = ['torque1','torque2','torque3','torque4','torque5','torque6','torque7','torque8','torque9']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       torque1,torque2,torque3,torque4,torque5,torque6,torque7,torque8,torque9

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Torques, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.torque1 is None:
        self.torque1 = 0.
      if self.torque2 is None:
        self.torque2 = 0.
      if self.torque3 is None:
        self.torque3 = 0.
      if self.torque4 is None:
        self.torque4 = 0.
      if self.torque5 is None:
        self.torque5 = 0.
      if self.torque6 is None:
        self.torque6 = 0.
      if self.torque7 is None:
        self.torque7 = 0.
      if self.torque8 is None:
        self.torque8 = 0.
      if self.torque9 is None:
        self.torque9 = 0.
    else:
      self.torque1 = 0.
      self.torque2 = 0.
      self.torque3 = 0.
      self.torque4 = 0.
      self.torque5 = 0.
      self.torque6 = 0.
      self.torque7 = 0.
      self.torque8 = 0.
      self.torque9 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.torque1, _x.torque2, _x.torque3, _x.torque4, _x.torque5, _x.torque6, _x.torque7, _x.torque8, _x.torque9))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.torque1, _x.torque2, _x.torque3, _x.torque4, _x.torque5, _x.torque6, _x.torque7, _x.torque8, _x.torque9,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.torque1, _x.torque2, _x.torque3, _x.torque4, _x.torque5, _x.torque6, _x.torque7, _x.torque8, _x.torque9))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.torque1, _x.torque2, _x.torque3, _x.torque4, _x.torque5, _x.torque6, _x.torque7, _x.torque8, _x.torque9,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9f = None
def _get_struct_9f():
    global _struct_9f
    if _struct_9f is None:
        _struct_9f = struct.Struct("<9f")
    return _struct_9f
